"""
Pydantic data models for request and response validation.
"""
from typing import List, Optional
from pydantic import BaseModel, Field

class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of the speaker: 'user' or 'assistant'")
    content: str = Field(..., description="Message text content")

class ChatRequest(BaseModel):
    session_id: str = Field(..., min_length=1, description="Client-generated unique session UUID")
    question: str = Field(..., min_length=1, description="The user's question")
    history: List[ChatMessage] = Field(default_factory=list, description="Prior conversation turns for context")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer text generated by Gemini")
    sources: List[str] = Field(default_factory=list, description="List of source filenames cited in the answer")

class DocumentInfo(BaseModel):
    filename: str
    chunk_count: int

class FileProcessResult(BaseModel):
    filename: str
    status: str  # "success" or "failed"
    chunks: int = 0
    error: Optional[str] = None

class UploadResponse(BaseModel):
    session_id: str
    processed_files: List[FileProcessResult]
    documents: List[DocumentInfo]
    total_chunks: int
    message: str

class SessionInfoResponse(BaseModel):
    session_id: str
    documents: List[DocumentInfo]
    total_chunks: int
